# Generated by Django 6.0.7 on 2026-07-24 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('profession', models.CharField(max_length=150, verbose_name='Profesión')),
                ('short_description', models.CharField(max_length=150, verbose_name='Descripción Corta')),
                ('about', models.TextField(verbose_name='Acerca de')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='biography/', verbose_name='Imagen de Perfil')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/', verbose_name='CV')),
                ('available_for_work', models.BooleanField(default=True, verbose_name='Disponible para Trabajo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Biografía',
                'verbose_name_plural': 'Biografías',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=150, verbose_name='Institución')),
                ('degree', models.CharField(max_length=200, verbose_name='Título o programa')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('institution_logo', models.ImageField(blank=True, null=True, upload_to='education/', verbose_name='Logo de la institución')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('currently_studying', models.BooleanField(default=False, verbose_name='¿Cursa actualmente?')),
                ('certificate_url', models.URLField(blank=True, verbose_name='Certificado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='¿Es Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Título del Proyecto')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=200, verbose_name='Descripción Corta')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbnails/', verbose_name='Miniatura')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Repositorio de Github')),
                ('demo_url', models.URLField(blank=True, null=True, verbose_name='Demo')),
                ('status', models.CharField(choices=[('completed', 'Completado'), ('in_progress', 'En progreso'), ('archived', 'Archivado')], default='In Progress', max_length=20, verbose_name='Estado')),
                ('featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='¿Es Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Red Social')),
                ('icon', models.CharField(max_length=100, verbose_name='Ícono de la Red Social')),
                ('url', models.URLField(verbose_name='URL de la Red Social')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='¿Es Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Red Social',
                'verbose_name_plural': 'Redes Sociales',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('language', 'Lenguaje'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Base de datos'), ('devops', 'DevOps'), ('tool', 'Herramienta')], default='language', max_length=50, verbose_name='Categoría')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Tecnología')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='technologies/', verbose_name='Ícono')),
                ('level', models.PositiveSmallIntegerField(default=3, verbose_name='Nivel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='¿Es Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Tecnología',
                'verbose_name_plural': 'Tecnologías',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Imagen')),
                ('alt_text', models.CharField(blank=True, max_length=200, null=True, verbose_name='Texto Alternativo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_images', to='core.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Imagen del Proyecto',
                'verbose_name_plural': 'Imágenes de los Proyectos',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(related_name='projects', to='core.technology', verbose_name='Tecnologías'),
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150, verbose_name='Empresa')),
                ('position', models.CharField(max_length=150, verbose_name='Cargo')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='experience/', verbose_name='Logo de la Empresa')),
                ('location', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ubicación')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('current_job', models.BooleanField(default=False, verbose_name='¿Trabajo Actual?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_visible', models.BooleanField(default=True, verbose_name='¿Es Visible?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('technologies', models.ManyToManyField(blank=True, related_name='experiences', to='core.technology', verbose_name='Tecnologías')),
            ],
            options={
                'verbose_name': 'Experiencia Laboral',
                'verbose_name_plural': 'Experiencias Laborales',
                'ordering': ['order', '-start_date'],
            },
        ),
    ]
