# Generated by Django 6.0.7 on 2026-07-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biography',
            name='cv',
            field=models.FileField(default=1, upload_to='cv/', verbose_name='Hoja de vida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='biography',
            name='profile_picture',
            field=models.ImageField(default=1, upload_to='biography/', verbose_name='Foto de perfil'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='institution_logo',
            field=models.ImageField(default=1, upload_to='education/', verbose_name='Logo de la institución'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='technologies/', verbose_name='icono'),
        ),
    ]
